---
# SITE4 variables
# Use eBGP as underlay routing protocol on SITE4, the default is 'none' for WAN routers.
underlay_routing_protocol: ebgp

# Spine switch group
spine:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 192.168.255.0/24
    bgp_as: 65105

  nodes:
    - name: site4-spine1
      id: 17
      mgmt_ip: 192.168.17.45/24

l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.42.0/24
    filter:
      always_include_vrfs_in_tenants: [all]
    mlag_interfaces: [Ethernet5, Ethernet6]
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    mlag_peer_ipv4_pool: 10.255.252.0/24
  node_groups:
    - group: SITE4
      bgp_as: 65104
      nodes:
        - name: site4-border1
          mgmt_ip: 192.168.17.41/24
          id: 13
        - name: site4-border2
          mgmt_ip: 192.168.17.42/24
          id: 14

wan_router:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.42.0/24
    uplink_ipv4_pool: 10.0.4.0/24
    filter:
      always_include_vrfs_in_tenants: [all]
    uplink_interfaces: [Ethernet1, Ethernet2]
    uplink_switches: [site4-spine1]
    uplink_type: p2p-vrfs # (1)!
    bgp_as: 65000
  node_groups:
    - group: SITE4
      cv_pathfinder_region: REGION3
      cv_pathfinder_site: SITE4
      # Making this site a transit site
      cv_pathfinder_transit_mode: region # (2)!
      wan_ha:
        enabled: true
        # Use this knob to disable IPSec on WAN HA tunnel(s)
        # ipsec: false
      nodes:
        - name: site4-wan1
          id: 15
          evpn_role: client
          mgmt_ip: 192.168.17.43/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
          l3_interfaces:
            - name: Ethernet3
              profile: MPLS-WAN-INTERFACE
              peer_interface: Ethernet5
              peer_ip: 172.18.40.1
              ip_address: 172.18.40.2/24
              wan_carrier: ACME-MPLS-INC
              wan_circuit_id: mpls-site4-wan1
            - name: Ethernet4
              peer_interface: Ethernet5
              peer_ip: 100.64.40.1
              ip_address: 100.64.40.2/24
              profile: INTERNET-WAN-INTERFACE
              wan_carrier: REGION3-INTERNET-CORP
              wan_circuit_id: inet-site4-wan1
        - name: site4-wan2
          id: 16
          mgmt_ip: 192.168.17.44/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
          l3_interfaces:
            - name: Ethernet3
              profile: MPLS-WAN-INTERFACE
              peer_interface: Ethernet6
              peer_ip: 172.18.41.1
              ip_address: 172.18.41.2/24
              wan_carrier: ACME-MPLS-INC
              wan_circuit_id: mpls-site4-wan2
            - name: Ethernet4
              peer_interface: Ethernet6
              dhcp_ip: 100.64.41.2
              profile: INTERNET-WAN-INTERFACE
              wan_carrier: REGION3-INTERNET-CORP
              wan_circuit_id: inet-site4-wan2
